baseURL = "https://fibra.click"
languageCode = "it-IT"
title = "FibraClick Wiki"

theme = "hugo-journal"

disableKinds = ["RSS", "taxonomyTerm"]
preserveTaxonomyNames = true
footnoteReturnLinkContents = "⤴"
removePathAccents = true

[params]
  homeTitle = "FibraClick Wiki, risposte sulla fibra ottica"
  description = "Dubbi sulla fibra ottica, copertura o intervento pubblico? FibraClick Wiki è lo spazio dedicato dove trovare risposte precise e curate."
  analytics = "UA-65084561-3"

[permalinks]
  posts = "/:slug"
  categories = "/c/:slug"

[taxonomies]
  category = "categories"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
